### ISSUE TITLE
How to get value of inputted date?

### ISSUE THREAD

**Issue by artawood** [arthurdenner/react-semantic-ui-datepickers#144]
Got a question. How do I get the value of the inputted date on the onChange event? 
I'm using react hook
`const [currentDate, setNewDate] = useState("")`
Here's the code
`<SemanticDatepicker onChange={evt => setNewDate(evt.target.value)}/>`

I tried following the example in the Codepen with `onDateChange` but that doesn't seem to work in the new version.

**Comment by arthurdenner** [comment]
Hi @artawood! :wave: 

Sorry for the wait to reply, I'm taking a quick vacation.

So, since `2.0.0`, the signature for the `onChange` prop is similar to the `semantic-ui-react` library, which means `(event, data)`, and inside `data` there is a `value` property.

I never noticed that we don't let this clear on the documentation, would you like to submit a PR to add it? Let me know if you would or not so that I can work on it if you wouldn't.

**Comment by artawood** [comment]
@arthurdenner For sure! I have the edits ready to push. Can you grant me access so I can submit a PR? Thanks.

**Comment by arthurdenner** [comment]
Nice! You can follow the [contribution guidelines](https://github.com/arthurdenner/react-semantic-ui-datepickers/blob/develop/CONTRIBUTING.md) to get your PR submitted.

**Comment by artawood** [comment]
Hi @arthurdenner, here's the PR: https://github.com/arthurdenner/react-semantic-ui-datepickers/pull/145
Let me know if this helps.
