### ISSUE TITLE
Form.input  format is not a function 

### ISSUE THREAD

**Issue by chrishj59** [arthurdenner/react-semantic-ui-datepickers#239]
# 🐛 bug report
The option format="DD/MM/YYY"  doegenerates an error - TypeError Format is not a function

## Description of the problem
I need the date to display in European format DD/MM/YYYY.
Where the SemanticDatepicker is used outside a Redux Form Field it is possible to use the format option to set the date format. This does not work within a Form.input

## How has this issue affected you? What are you trying to accomplish?
As the main usage is outside the USA iIneed the format to be in the UK format of DD/MM/YYY

[datePicker.pdf](https://github.com/arthurdenner/react-semantic-ui-datepickers/files/4477179/datePicker.pdf)

**Comment by arthurdenner** [comment]
Hi @chrishj59! 👋

I'm not sure if I understand your issue and I'm not able to run your code since it requires redux-form to be setup and everything, but I've built [this example](https://codesandbox.io/s/react-semantic-ui-datepickers-example-hrs8n?file=/src/index.js:904-931) showing how to use this library with the format "DD/MM/YYYY".

I hope it helps. If it doesn't, please provide a sandbox with a reproducible example - forking the link above is a good starting point.

**Comment by chrishj59** [comment]
I have created the repo that shows the issue. If you add the property format "DD/MM/YYYY" the component generates the error format not known
https://github.com/chrishj59/datepickerIssue

**Comment by arthurdenner** [comment]
@chrishj59, your repo has only one commit from CRA, nothing else. Maybe you forgot to push?

**Comment by chrishj59** [comment]
My Apologies - I had forgotten to run commit .
The file with just the date picker is  datepickerIssue/src/components/SongList.js

Many thanks

Chris

**Comment by arthurdenner** [comment]
@chrishj59, you are getting an error because the `Field` component from `redux-form` has also a prop called [`format`](https://redux-form.com/8.3.0/docs/api/field.md/#-code-format-value-name-gt-formattedvalue-code-optional-). Fortunately, redux-form pass down any prop that it's not in its API, so you do the following:

1. Create a new component that will map a "new" `dateFormat` prop to the `format` prop from this library and pass down the rest:
```jsx
const CustomDatepicker = ({ dateFormat, ...rest }) => (
  <SemanticDatepicker {...rest} format={dateFormat} />
);
```

2. Use this new component with the `Field`:

```jsx
<Field
  component={CustomDatepicker}
  dateFormat="DD/MM/YYYY" // <-- use the "new" prop instead
  name="working"
  label="Date of birth"
  placeholder="select your DOB"
  size="small"
/>
```

I hope this helps. Let me know if you have any other question. 👋

**Comment by chrishj59** [comment]
Thanks, this works like a dream!! :)
