### ISSUE TITLE
Inline version of datepicker

### ISSUE THREAD

**Issue by kasugaicrow** [arthurdenner/react-semantic-ui-datepickers#282]
# ❔ Question

Hi,
I have implemented react-semantic-ui-datepickers inside my react application and everything works fine, but I have a question. Is there a way to display the datepicker inline? I mean without the need to click inside the textbox and wait for the popup to appear. A way to display only the actual datepicker ready to use.

Thanks

**Comment by arthurdenner** [comment]
Hi @kasugaicrow! 👋 

There wasn't a way, but I've created a PR adding support to it and released `2.7.0-beta.0` so that you can test and see if it fits your needs.

You can also check it [here](https://react-semantic-ui-datepickers-fxoutao4j.now.sh/?path=/story/datepickers--basic-usage), by toggling the "Inline (without the input)" checkbox.

**Comment by kasugaicrow** [comment]
Hi @arthurdenner!
I checked your PR and the example on the storybook and it perfectly fits my requirements.

Thank you so much for your work!

**Comment by arthurdenner** [comment]
Awesome. Then I'll merge the PR and release it. Thank you for the suggestion.
