### ISSUE TITLE
Calender date get distorted in internet explorer 11

### ISSUE THREAD

**Issue by Ellipticamit** [arthurdenner/react-semantic-ui-datepickers#29]
]# 🐛 bug report

When date picker is open in Internet Explorer 11. The tabular form of date number gets distorted.

You can try to open this link:  https://react-semantic-ui-datepickers.now.sh in IE 11

![ie11issue](https://user-images.githubusercontent.com/5086469/59141393-d070dc80-89c9-11e9-8bf5-06e6c4aa9c49.PNG)

**Comment by arthurdenner** [comment]
Hi @Ellipticamit! :wave: 

Thanks for reporting the bug.

Maybe this has something to do with the IE11 support to CSS Grid (which is only [partial](https://caniuse.com/#feat=css-grid))?

Feel free to send a PR with a fix, but unfortunately I'm not planning to work on this since I don't need to support IE11 and I'm not using the library at my current work, so it's not being actively maintained as before.
