### ISSUE TITLE
How will get current filed id or name ? 

### ISSUE THREAD

**Issue by rohitkkrana** [arthurdenner/react-semantic-ui-datepickers#33]
# ❔ Question

Suppose we have two people his name is jhon,tony and that list is dynamic it may be increase, so we need to get the get the name or id of current field event. how can we recognise it?

**Comment by arthurdenner** [comment]
Hi @rohitkkrana! :wave: 

I'm sorry, but I didn't understand what you meant. Could you explain more or provide a sandbox reproducing your question?

Thanks in advance!

**Comment by rohitkkrana** [comment]
Please check 
https://codesandbox.io/s/async-sound-bu1f5?fontsize=14

**Comment by arthurdenner** [comment]
Thanks @rohitkkrana! I think I understand what you mean now.

This is somewhat related to #30, because the `onDateChange` prop is called only with the new date, nothing else. I think I'll refactor this library in the next few weeks to improve it.

Right now, you can workaround this behaviour in the following way:

- Replace your `onDateChange` with:
```
onDateChange={newDate => this.checkDate(v, newDate)}
```
- Update your `checkDate` method with:
```
checkDate = (user, newDate) => {
    console.log(user, newDate);
  };
```
And then you will have a way to identify which user is related to the date selection.

Let me know if you have any other question or if my suggestion does not solve your problem.

**Comment by rohitkkrana** [comment]
Thanks and great job this module is so awesome. Thanks once again for you and your team...
