### ISSUE TITLE
Missing props in SemmaticDatepickerProps interface definition

### ISSUE THREAD

**Issue by bf39l** [arthurdenner/react-semantic-ui-datepickers#44]
# ❔ Question
I am working on a project written by typescript and I would like to use ReadOnly props in SemmaticDatepicker, then I got compile error because readOnly is not defined in interface SemanticDatepickerProps. Following codes are from "react-semantic-ui-datepickers/dist/index.d.ts"

```
export interface SemanticDatepickerProps {
  clearable?: boolean;
  date?: Date;
  disabled?: boolean;
  error?: boolean;
  firstDayOfWeek?: number;
  format?: string;
  icon?: SemanticICONS;
  iconPosition?: 'left';
  id?: string;
  keepOpenOnClear?: boolean;
  keepOpenOnSelect?: boolean;
  label?: string;
  loading?: boolean;
  locale?: Locale;
  maxDate?: Date;
  minDate?: Date;
  name?: string;
  onDateChange: (newDate: Date | Date[] | null) => void;
  placeholder?: string;
  pointing: 'left' | 'right' | 'top left' | 'top right';
  selected?: Date | Date[];
  showOutsideDays?: boolean;
  size?: SemanticSIZES;
  transparent?: boolean;
  type: 'basic' | 'range';
}
```

**Comment by arthurdenner** [comment]
Hi @bf39l! 👋 

Thanks for reporting this. Since the typings are currently maintained manually, this kind of thing happens... but not for long.

I'm working on a branch that converts the component to TypeScript so the typings are generated automatically. I'll probably release a new version of the library with these changes this week and your issue will be solved.

But, if you need a fix ASAP, feel free to send a PR fixing the typings and I'll gladly merge it (or let me know and I'll send one).
