### ISSUE TITLE
Datepicker text unreadable due to CSS styling

### ISSUE THREAD

**Issue by AntonStrickland** [arthurdenner/react-semantic-ui-datepickers#694]
# 🐛 bug report

I don't know if this is a bug with the code or if I'm just doing something wrong.

## Description of the problem
The default text of the datepicker is black, but when I use CSS to modify my text across my entire app to white, the text inside the datepicker also changes to white, making it unreadable. This is for the name of the month, the days of the week, and the numbers of each day. Trying to style the datepicker individually does not seem to work. Here is what I am doing and what I have tried to fix it (just the important parts of the code):

style/index.js:
```
`import styled from "styled-components";

export const Body = styled.div
  background-color: #282c34;
  color: white;
;`
```

Component.js:
```
import SemanticDatepicker from 'react-semantic-ui-datepickers';
import 'react-semantic-ui-datepickers/dist/react-semantic-ui-datepickers.css';

const Component = () => {
return (<SemanticDatepicker style={{color: "black"}} onChange={onChange} /> );
}
```

App.js:
```
import { Body } from "./components/style";
import { Component } from "./components/Component";

<Body>
<Component/>
</Body>
```

## How has this issue affected you? What are you trying to accomplish?
I would like to have an app that has a dark background with white text on it. The datepicker's text turns white, making all of the dates unreadable. I would like to be able to change the datepicker's text to black (or any other color) while keeping the rest of my app's text white. Or also a way to change the background of the datepicker to black while keeping the white text would also work. 

Note that I am using plenty of other semantic-ui-react components but it is only this one that changes its text from black to white. And as stated I've already tried changing the CSS for this specific component but it's not doing anything. The only thing that affects the SemanticDatepicker is when I change the CSS in the Body component. So that's why I think it's an issue.

**Comment by arthurdenner** [comment]
Hi @AntonStrickland!

I'm sorry for the wait to reply, I haven't been able to look at my GitHub lately.
I hope you have found a solution but I'll drop my thoughts here.

Some elements have classes that allow customization because they use `color: inherit`:
https://github.com/arthurdenner/react-semantic-ui-datepickers#customization

You should be able to target one of them from your CSS rule, for example:
https://codesandbox.io/s/react-semantic-ui-datepickers-custom-css-ginsw?file=/src/index.js
You can also use the `inverted` prop if you want to use the default Semantic UI "dark mode".

Please let me know if one of these solves your issue or if you've solved it in a different way.
Also, feel free to report any unexpected behaviour if you think there is any 🙏🏽
